--ALTER 
 CREATE
VIEW [dbo].[AL_BorderouAchizitieLunaraLapte] AS
SELECT
BordAchizLapte.Data_lunii AS BordAchizLapte_Data_lunii,
CASE BordAchizLapte.Tip 
WHEN 'I' THEN 'Initiala' WHEN 'L' THEN 'Lunara' WHEN 'Z' THEN 'Zilnica' ELSE BordAchizLapte.Tip END
AS BordAchizLapte_Tip,
RTRIM(BordAchizLapte.Producator)+' '+RTRIM(ProdLapte.Denumire) AS BordAchizLapte_Producator,
REPLICATE('0',3-LEN(RTRIM(BordAchizLapte.Centru_colectare)))
+RTRIM(BordAchizLapte.Centru_colectare)+' '+RTRIM(CentrColectLapte.Denumire) AS BordAchizLapte_Centru_colectare,
BordAchizLapte.Cant_UM AS BordAchizLapte_Cant_UM,
BordAchizLapte.Grasime AS BordAchizLapte_Grasime,
BordAchizLapte.Cant_UG AS BordAchizLapte_Cant_UG,
BordAchizLapte.Cant_STAS AS BordAchizLapte_Cant_STAS,
BordAchizLapte.Pret AS BordAchizLapte_Pret,
BordAchizLapte.Valoare AS BordAchizLapte_Valoare,
BordAchizLapte.Data_operarii AS BordAchizLapte_Data_operarii,
BordAchizLapte.Ora_operarii AS BordAchizLapte_Ora_operarii,
BordAchizLapte.Utilizator AS BordAchizLapte_Utilizator,
CalStd.Data AS CalStd_Data,
CalStd.Data_lunii AS CalStd_Data_lunii,
CalStd.An AS CalStd_An,
CalStd.Luna AS CalStd_Luna,
CalStd.LunaAlfa AS CalStd_LunaAlfa,
CalStd.Zi AS CalStd_Zi,
CalStd.Saptamana AS CalStd_Saptamana,
CalStd.Trimestru AS CalStd_Trimestru,
CalStd.Zi_alfa AS CalStd_Zi_alfa,
CalStd.Camp1 AS CalStd_Camp1,
CalStd.Camp2 AS CalStd_Camp2,
CalStd.Camp3 AS CalStd_Camp3,
CalStd.Fel_zi AS CalStd_Fel_zi,
ProdLapte.Cod_producator AS ProdLapte_Cod_producator,
ProdLapte.Denumire AS ProdLapte_Denumire,
ProdLapte.Initiala_tatalui AS ProdLapte_Initiala_tatalui,
ProdLapte.Serie_buletin AS ProdLapte_Serie_buletin,
ProdLapte.Nr_buletin AS ProdLapte_Nr_buletin,
ProdLapte.Eliberat AS ProdLapte_Eliberat,
ProdLapte.CNP_CUI AS ProdLapte_CNP_CUI,
ProdLapte.Judet AS ProdLapte_Judet,
ProdLapte.Localitate AS ProdLapte_Localitate,
ProdLapte.Comuna AS ProdLapte_Comuna,
ProdLapte.Sat AS ProdLapte_Sat,
ProdLapte.Strada AS ProdLapte_Strada,
ProdLapte.Nr_str AS ProdLapte_Nr_str,
ProdLapte.Nr_casa AS ProdLapte_Nr_casa,
ProdLapte.Bloc AS ProdLapte_Bloc,
ProdLapte.Scara AS ProdLapte_Scara,
ProdLapte.Etaj AS ProdLapte_Etaj,
ProdLapte.Ap AS ProdLapte_Ap,
ProdLapte.Cod_exploatatie AS ProdLapte_Cod_exploatatie,
ProdLapte.Cota_actuala AS ProdLapte_Cota_actuala,
ProdLapte.Grad_actual AS ProdLapte_Grad_actual,
ProdLapte.Vaci AS ProdLapte_Vaci,
ProdLapte.Tip_pers AS ProdLapte_Tip_pers,
ProdLapte.Tert AS ProdLapte_Tert,
ProdLapte.Reprezentant AS ProdLapte_Reprezentant,
ProdLapte.CNP_repr AS ProdLapte_CNP_repr,
ProdLapte.Centru_colectare AS ProdLapte_Centru_colectare,
ProdLapte.Loc_de_munca AS ProdLapte_Loc_de_munca,
ProdLapte.Data_operarii AS ProdLapte_Data_operarii,
ProdLapte.Ora_operarii AS ProdLapte_Ora_operarii,
ProdLapte.Utilizator AS ProdLapte_Utilizator,
CentrColectLapte.Cod_centru_colectare AS CentrColectLapte_Cod_centru_colectare,
CentrColectLapte.Denumire AS CentrColectLapte_Denumire,
CentrColectLapte.Cod_IBAN AS CentrColectLapte_Cod_IBAN,
CentrColectLapte.Banca AS CentrColectLapte_Banca,
CentrColectLapte.Sat AS CentrColectLapte_Sat,
CentrColectLapte.Comuna AS CentrColectLapte_Comuna,
RTRIM(CentrColectLapte.Localitate)+' '+RTRIM(ISNULL(Localitati.oras, '')) AS CentrColectLapte_Localitate,
RTRIM(CentrColectLapte.Judet)+' '+RTRIM(ISNULL(Judete.denumire,'')) AS CentrColectLapte_Judet,
CentrColectLapte.Responsabil AS CentrColectLapte_Responsabil,
RTRIM(CentrColectLapte.Loc_de_munca)+' '+RTRIM(ISNULL(lm.Denumire,'')) AS CentrColectLapte_Loc_de_munca,
CentrColectLapte.Tip_pers AS CentrColectLapte_Tip_pers,
RTRIM(CentrColectLapte.Tert)+' '+RTRIM(ISNULL(terti.Denumire,'')) AS CentrColectLapte_Tert,
CentrColectLapte.Data_operarii AS CentrColectLapte_Data_operarii,
CentrColectLapte.Ora_operarii AS CentrColectLapte_Ora_operarii,
CentrColectLapte.Utilizator AS CentrColectLapte_Utilizator,
ISNULL(CentrColectProdLapte.Nr_ordine,0) AS CentrColectProdLapte_Nr_ordine,
CentrColectProdLapte.Data_inscrierii AS CentrColectProdLapte_Data_inscrierii,
CentrColectProdLapte.Nr_fisa AS CentrColectProdLapte_Nr_fisa,
CentrColectProdLapte.Data_operarii AS CentrColectProdLapte_Data_operarii,
CentrColectProdLapte.Ora_operarii AS CentrColectProdLapte_Ora_operarii,
CentrColectProdLapte.Utilizator AS CentrColectProdLapte_Utilizator,
BordAchizLapteVwUtilCotaAnaliza.Data_inc_an_cota AS BordAchizLapteVwUtilCotaAnaliza_Data_inc_an_cota,
BordAchizLapteVwUtilCotaAnaliza.Data_sf_an_cota AS BordAchizLapteVwUtilCotaAnaliza_Data_sf_an_cota,
BordAchizLapteVwUtilCotaAnaliza.An_cota AS BordAchizLapteVwUtilCotaAnaliza_An_cota,
BordAchizLapteVwUtilCotaAnaliza.Cant_UM_cota AS BordAchizLapteVwUtilCotaAnaliza_Cant_UM_cota,
BordAchizLapteVwUtilCotaAnaliza.Cant_UG_cota AS BordAchizLapteVwUtilCotaAnaliza_Cant_UG_cota,
BordAchizLapteVwUtilCotaAnaliza.Cota_utilizata_colecta AS BordAchizLapteVwUtilCotaAnaliza_Cota_utilizata_colecta,
BordAchizLapteVwUtilCotaAnaliza.Proc_utiliz_cota AS BordAchizLapteVwUtilCotaAnaliza_Proc_utiliz_cota,
BordAchizLapteVwUtilCotaAnaliza.Rezultat_analiza_lapte AS BordAchizLapteVwUtilCotaAnaliza_Rezultat_analiza_lapte,
UtilizareCotaProdAnColecta.Cant_UM AS UtilizareCotaProdAnColecta_Cant_UM,
UtilizareCotaProdAnColecta.Cant_UG AS UtilizareCotaProdAnColecta_Cant_UG,
UtilizareCotaProdAnColecta.Cant_STAS AS UtilizareCotaProdAnColecta_Cant_STAS,
UtilizareCotaProdAnColecta.Cant_UM_cota AS UtilizareCotaProdAnColecta_Cant_UM_cota,
UtilizareCotaProdAnColecta.Cant_UG_cota AS UtilizareCotaProdAnColecta_Cant_UG_cota,
UtilizareCotaProdAnColecta.Cant_STAS_UM_cota AS UtilizareCotaProdAnColecta_Cant_STAS_UM_cota,
UtilizareCotaProdAnColecta.Cota_utilizata AS UtilizareCotaProdAnColecta_Cota_utilizata,
UtilizareCotaProdAnColecta.Proc_utiliz_cota AS UtilizareCotaProdAnColecta_Proc_utiliz_cota,
UtilizareCotaProdAnColecta.Nr_luni_cota_ramase AS UtilizareCotaProdAnColecta_Nr_luni_cota_ramase,
UtilizareCotaProdAnColecta.Nr_luni_an_cota_ramase AS UtilizareCotaProdAnColecta_Nr_luni_an_cota_ramase,
UtilizareCotaProdAnColecta.Cant_UM_rest_cota AS UtilizareCotaProdAnColecta_Cant_UM_rest_cota,
UtilizareCotaProdAnColecta.Gras_medie_rest_cota AS UtilizareCotaProdAnColecta_Gras_medie_rest_cota,
UtilizareCotaProdAnColecta.Cant_UG_rest_cota AS UtilizareCotaProdAnColecta_Cant_UG_rest_cota,
UtilizareCotaProdAnColecta.Cant_STAS_rest_cota AS UtilizareCotaProdAnColecta_Cant_STAS_rest_cota,
UtilizareCotaProdAnColecta.Cant_UM_cota_rest_cota AS UtilizareCotaProdAnColecta_Cant_UM_cota_rest_cota,
UtilizareCotaProdAnColecta.Cant_UG_cota_rest_cota AS UtilizareCotaProdAnColecta_Cant_UG_cota_rest_cota,
UtilizareCotaProdAnColecta.Cant_STAS_UM_cota_rest_cota AS UtilizareCotaProdAnColecta_Cant_STAS_UM_cota_rest_cota,
lm.Cod AS lm_Cod,
lm.Denumire AS lm_Denumire,
terti.Tert AS terti_Tert,
terti.Denumire AS terti_Denumire,
terti.Cod_fiscal AS terti_Cod_fiscal,
terti.Localitate AS terti_Localitate,
terti.Judet AS terti_Judet,
terti.Adresa AS terti_Adresa,
terti.Telefon_fax AS terti_Telefon_fax,
terti.Banca AS terti_Banca,
terti.Cont_in_banca AS terti_Cont_in_banca,
terti.Tert_extern AS terti_Tert_extern,
terti.Grupa AS terti_Grupa,
terti.Cont_ca_furnizor AS terti_Cont_ca_furnizor,
terti.Cont_ca_beneficiar AS terti_Cont_ca_beneficiar,
terti.Sold_ca_furnizor AS terti_Sold_ca_furnizor,
terti.Sold_ca_beneficiar AS terti_Sold_ca_beneficiar,
terti.Sold_maxim_ca_beneficiar AS terti_Sold_maxim_ca_beneficiar,
terti.Disccount_acordat AS terti_Disccount_acordat,
Judete.cod_judet AS Judete_cod_judet,
Judete.denumire AS Judete_denumire,
Localitati.cod_oras AS Localitati_cod_oras,
Localitati.cod_judet AS Localitati_cod_judet,
Localitati.oras AS Localitati_oras
FROM BordAchizLapte
LEFT JOIN CalStd ON CalStd.Data= BordAchizLapte.Data_lunii
LEFT JOIN ProdLapte ON BordAchizLapte.Producator= ProdLapte.Cod_producator
LEFT JOIN CentrColectLapte ON BordAchizLapte.Centru_colectare= CentrColectLapte.Cod_centru_colectare
LEFT JOIN CentrColectProdLapte 
	ON CentrColectProdLapte.Producator= BordAchizLapte.Producator
	AND CentrColectProdLapte.Centru_colectare= BordAchizLapte.Centru_colectare
LEFT JOIN BordAchizLapteVwUtilCotaAnaliza 
	ON BordAchizLapteVwUtilCotaAnaliza.Data_lunii=BordAchizLapte.Data_lunii
	AND BordAchizLapteVwUtilCotaAnaliza.Tip=BordAchizLapte.Tip
	AND BordAchizLapteVwUtilCotaAnaliza.Producator=BordAchizLapte.Producator
	AND BordAchizLapteVwUtilCotaAnaliza.Centru_colectare=BordAchizLapte.Centru_colectare
LEFT JOIN UtilizareCotaProdAnColecta ON UtilizareCotaProdAnColecta.Producator= ProdLapte.Cod_producator
LEFT JOIN lm ON CentrColectLapte.Tip_pers='F' AND CentrColectLapte.Loc_de_munca= lm.cod
LEFT JOIN terti ON CentrColectLapte.Tip_pers='J' AND CentrColectLapte.Tert= terti.tert
LEFT JOIN judete ON judete.cod_judet= CentrColectLapte.Judet
LEFT JOIN localitati ON localitati.cod_oras= CentrColectLapte.Localitate