CREATE VIEW [AL_UtilizareCotaProdAnCurent] AS
SELECT
RTRIM(UtilizareCotaProdAnCurent.Producator)+' '+RTRIM(ISNULL(ProdLapte.Denumire,'')) AS UtilizareCotaProdAnCurent_Producator,
RTRIM(UtilizareCotaProdAnCurent.Centru_colectare)+' '+RTRIM(ISNULL(CentrColectLapte.Denumire,'')) AS UtilizareCotaProdAnCurent_Centru_colectare,
UtilizareCotaProdAnCurent.Data_lunii AS UtilizareCotaProdAnCurent_Data_lunii,
UtilizareCotaProdAnCurent.Data_inc_an_cota AS UtilizareCotaProdAnCurent_Data_inc_an_cota,
UtilizareCotaProdAnCurent.Data_sf_an_cota AS UtilizareCotaProdAnCurent_Data_sf_an_cota,
UtilizareCotaProdAnCurent.An_cota AS UtilizareCotaProdAnCurent_An_cota,
UtilizareCotaProdAnCurent.Cant_UM AS UtilizareCotaProdAnCurent_Cant_UM,
UtilizareCotaProdAnCurent.Cant_UG AS UtilizareCotaProdAnCurent_Cant_UG,
UtilizareCotaProdAnCurent.Cant_STAS AS UtilizareCotaProdAnCurent_Cant_STAS,
UtilizareCotaProdAnCurent.Cant_UM_cota AS UtilizareCotaProdAnCurent_Cant_UM_cota,
UtilizareCotaProdAnCurent.Cant_UG_cota AS UtilizareCotaProdAnCurent_Cant_UG_cota,
UtilizareCotaProdAnCurent.Cant_STAS_UM_cota AS UtilizareCotaProdAnCurent_Cant_STAS_UM_cota,
UtilizareCotaProdAnCurent.Grad_actual AS UtilizareCotaProdAnCurent_Grad_actual,
UtilizareCotaProdAnCurent.Cota_actuala AS UtilizareCotaProdAnCurent_Cota_actuala,
UtilizareCotaProdAnCurent.Cota_utilizata AS UtilizareCotaProdAnCurent_Cota_utilizata,
UtilizareCotaProdAnCurent.Proc_utiliz_cota AS UtilizareCotaProdAnCurent_Proc_utiliz_cota,
UtilizareCotaProdAnCurent.Nr_livrari_efectuate AS UtilizareCotaProdAnCurent_Nr_livrari_efectuate,
UtilizareCotaProdAnCurent.Nr_luni_colecta_ramase AS UtilizareCotaProdAnCurent_Nr_luni_colecta_ramase,
UtilizareCotaProdAnCurent.Nr_luni_an_cota_ramase AS UtilizareCotaProdAnCurent_Nr_luni_an_cota_ramase,
UtilizareCotaProdAnCurent.Cant_UM_rest_cota AS UtilizareCotaProdAnCurent_Cant_UM_rest_cota,
UtilizareCotaProdAnCurent.Gras_medie_rest_cota AS UtilizareCotaProdAnCurent_Gras_medie_rest_cota,

UtilizareCotaCentrAnCurent.Centru_colectare AS UtilizareCotaCentrAnCurent_Centru_colectare,
UtilizareCotaCentrAnCurent.Producator AS UtilizareCotaCentrAnCurent_Producator,
UtilizareCotaCentrAnCurent.Data_lunii AS UtilizareCotaCentrAnCurent_Data_lunii,
UtilizareCotaCentrAnCurent.Data_inc_an_cota AS UtilizareCotaCentrAnCurent_Data_inc_an_cota,
UtilizareCotaCentrAnCurent.Data_sf_an_cota AS UtilizareCotaCentrAnCurent_Data_sf_an_cota,
UtilizareCotaCentrAnCurent.An_cota AS UtilizareCotaCentrAnCurent_An_cota,
UtilizareCotaCentrAnCurent.Cant_UM AS UtilizareCotaCentrAnCurent_Cant_UM,
UtilizareCotaCentrAnCurent.Cant_UG AS UtilizareCotaCentrAnCurent_Cant_UG,
UtilizareCotaCentrAnCurent.Cant_STAS AS UtilizareCotaCentrAnCurent_Cant_STAS,
UtilizareCotaCentrAnCurent.Cant_UM_cota AS UtilizareCotaCentrAnCurent_Cant_UM_cota,
UtilizareCotaCentrAnCurent.Cant_UG_cota AS UtilizareCotaCentrAnCurent_Cant_UG_cota,
UtilizareCotaCentrAnCurent.Cant_STAS_UM_cota AS UtilizareCotaCentrAnCurent_Cant_STAS_UM_cota,
UtilizareCotaCentrAnCurent.Grad_actual AS UtilizareCotaCentrAnCurent_Grad_actual,
UtilizareCotaCentrAnCurent.Cota_actuala AS UtilizareCotaCentrAnCurent_Cota_actuala,
UtilizareCotaCentrAnCurent.Nr_livrari_efectuate AS UtilizareCotaCentrAnCurent_Nr_livrari_efectuate,
UtilizareCotaCentrAnCurent.Gras_medie_rest_cota AS UtilizareCotaCentrAnCurent_Gras_medie_rest_cota,

ProdLapte.Cod_producator AS ProdLapte_Cod_producator,
ProdLapte.Denumire AS ProdLapte_Denumire,
ProdLapte.Initiala_tatalui AS ProdLapte_Initiala_tatalui,
ProdLapte.Serie_buletin AS ProdLapte_Serie_buletin,
ProdLapte.Nr_buletin AS ProdLapte_Nr_buletin,
ProdLapte.Eliberat AS ProdLapte_Eliberat,
ProdLapte.CNP_CUI AS ProdLapte_CNP_CUI,
RTRIM(ProdLapte.Judet)+' '+RTRIM(ISNULL(Judete.denumire,'')) AS ProdLapte_Judet,
RTRIM(ProdLapte.Localitate)+' '+RTRIM(ISNULL(Localitati.oras, '')) AS ProdLapte_Localitate,
ProdLapte.Comuna AS ProdLapte_Comuna,
ProdLapte.Sat AS ProdLapte_Sat,
ProdLapte.Strada AS ProdLapte_Strada,
ProdLapte.Nr_str AS ProdLapte_Nr_str,
ProdLapte.Nr_casa AS ProdLapte_Nr_casa,
ProdLapte.Bloc AS ProdLapte_Bloc,
ProdLapte.Scara AS ProdLapte_Scara,
ProdLapte.Etaj AS ProdLapte_Etaj,
ProdLapte.Ap AS ProdLapte_Ap,
ProdLapte.Cod_exploatatie AS ProdLapte_Cod_exploatatie,
ProdLapte.Cota_actuala AS ProdLapte_Cota_actuala,
ProdLapte.Grad_actual AS ProdLapte_Grad_actual,
ProdLapte.Vaci AS ProdLapte_Vaci,
ProdLapte.Grupa AS ProdLapte_Grupa,
ProdLapte.Pret AS ProdLapte_Pret,
ProdLapte.Tip_pers AS ProdLapte_Tip_pers,
RTRIM(ProdLapte.Tert)+' '+RTRIM(ISNULL(terti.Denumire,'')) AS ProdLapte_Tert,
ProdLapte.Reprezentant AS ProdLapte_Reprezentant,
ProdLapte.CNP_repr AS ProdLapte_CNP_repr,
ProdLapte.Centru_colectare AS ProdLapte_Centru_colectare,
ProdLapte.Loc_de_munca AS ProdLapte_Loc_de_munca,
ProdLapte.Data_operarii AS ProdLapte_Data_operarii,
ProdLapte.Ora_operarii AS ProdLapte_Ora_operarii,
ProdLapte.Utilizator AS ProdLapte_Utilizator,
CentrColectLapte.Cod_centru_colectare AS CentrColectLapte_Cod_centru_colectare,
CentrColectLapte.Denumire AS CentrColectLapte_Denumire,
CentrColectLapte.Cod_IBAN AS CentrColectLapte_Cod_IBAN,
CentrColectLapte.Banca AS CentrColectLapte_Banca,
CentrColectLapte.Sat AS CentrColectLapte_Sat,
CentrColectLapte.Comuna AS CentrColectLapte_Comuna,
CentrColectLapte.Localitate AS CentrColectLapte_Localitate,
CentrColectLapte.Judet AS CentrColectLapte_Judet,
CentrColectLapte.Responsabil AS CentrColectLapte_Responsabil,
RTRIM(CentrColectLapte.Loc_de_munca)+' '+RTRIM(ISNULL(lm.Denumire,'')) AS CentrColectLapte_Loc_de_munca,
CentrColectLapte.Tip_pers AS CentrColectLapte_Tip_pers,
CentrColectLapte.Tert AS CentrColectLapte_Tert,
CentrColectLapte.Data_operarii AS CentrColectLapte_Data_operarii,
CentrColectLapte.Ora_operarii AS CentrColectLapte_Ora_operarii,
CentrColectLapte.Utilizator AS CentrColectLapte_Utilizator,

CalStd.Data AS CalStd_Data,
CalStd.Data_lunii AS CalStd_Data_lunii,
CalStd.An AS CalStd_An,
CalStd.Luna AS CalStd_Luna,
CalStd.LunaAlfa AS CalStd_LunaAlfa,
CalStd.Zi AS CalStd_Zi,
CalStd.Saptamana AS CalStd_Saptamana,
CalStd.Trimestru AS CalStd_Trimestru,
CalStd.Zi_alfa AS CalStd_Zi_alfa,
CalStd.Camp1 AS CalStd_Camp1,
CalStd.Camp2 AS CalStd_Camp2,
CalStd.Camp3 AS CalStd_Camp3,
CalStd.Fel_zi AS CalStd_Fel_zi,

lm.Cod AS lm_Cod,
lm.Denumire AS lm_Denumire,
terti.Tert AS terti_Tert,
terti.Denumire AS terti_Denumire,
terti.Cod_fiscal AS terti_Cod_fiscal,
terti.Localitate AS terti_Localitate,
terti.Judet AS terti_Judet,
terti.Adresa AS terti_Adresa,
terti.Telefon_fax AS terti_Telefon_fax,
terti.Banca AS terti_Banca,
terti.Cont_in_banca AS terti_Cont_in_banca,
terti.Tert_extern AS terti_Tert_extern,
terti.Grupa AS terti_Grupa,
terti.Cont_ca_furnizor AS terti_Cont_ca_furnizor,
terti.Cont_ca_beneficiar AS terti_Cont_ca_beneficiar,
terti.Sold_ca_furnizor AS terti_Sold_ca_furnizor,
terti.Sold_ca_beneficiar AS terti_Sold_ca_beneficiar,
terti.Sold_maxim_ca_beneficiar AS terti_Sold_maxim_ca_beneficiar,
terti.Disccount_acordat AS terti_Disccount_acordat,
Judete.cod_judet AS Judete_cod_judet,
Judete.denumire AS Judete_denumire,
Localitati.cod_oras AS Localitati_cod_oras,
Localitati.cod_judet AS Localitati_cod_judet,
Localitati.oras AS Localitati_oras
/*
select 
rtrim(t.name)
--'IntrariLapteCompartimente'
+'.'+rtrim(ltrim(c.name))+' AS '
+rtrim(t.name)
--+'IntrariLapteCompartimente'
+'_'+rtrim(ltrim(c.name))+','
from sysobjects t 
	inner join syscolumns c on t.id=c.id
where t.name='UtilizareCotaCentrAnCurent'
*/
FROM UtilizareCotaProdAnCurent
	LEFT JOIN UtilizareCotaCentrAnCurent ON UtilizareCotaCentrAnCurent.Centru_colectare= UtilizareCotaProdAnCurent.Centru_colectare
	LEFT JOIN ProdLapte ON UtilizareCotaProdAnCurent.Producator= ProdLapte.Cod_producator
	LEFT JOIN CentrColectLapte ON UtilizareCotaProdAnCurent.Centru_colectare= CentrColectLapte.Cod_centru_colectare	
	LEFT JOIN CalStd ON CalStd.Data= UtilizareCotaProdAnCurent.Data_lunii
	LEFT JOIN terti ON ProdLapte.Tert= terti.tert
	LEFT JOIN lm ON CentrColectLapte.Loc_de_munca= lm.cod	
	LEFT JOIN judete ON judete.cod_judet= CentrColectLapte.Judet
	LEFT JOIN localitati ON localitati.cod_oras= CentrColectLapte.Localitate