

CREATE VIEW [dbo].[CG_IntrariLapteCalitativScriptic] AS
select
	IntrariLapteCalitativScriptic.Subunitate AS IntrariLapteCalitativScriptic_Subunitate,
	IntrariLapteCalitativScriptic.Tip AS IntrariLapteCalitativScriptic_Tip,
	IntrariLapteCalitativScriptic.Numar AS IntrariLapteCalitativScriptic_Numar,
	IntrariLapteCalitativScriptic.Data AS IntrariLapteCalitativScriptic_Data,
	IntrariLapteCalitativScriptic.Numar_pozitie AS IntrariLapteCalitativScriptic_Numar_pozitie,
	IntrariLapteCalitativScriptic.Data_cursa AS IntrariLapteCalitativScriptic_Data_cursa,
	RTRIM(IntrariLapteCalitativScriptic.Masina)+' '+LTRIM(ISNULL(comenzi.Descriere,'')) AS IntrariLapteCalitativScriptic_Masina,
	IntrariLapteCalitativScriptic.Tura AS IntrariLapteCalitativScriptic_Tura,
	RTRIM(IntrariLapteCalitativScriptic.Tip_lapte)+' '+LTRIM(ISNULL(nomencl.Denumire,'')) AS IntrariLapteCalitativScriptic_Tip_lapte,
	IntrariLapteCalitativScriptic.Compartiment AS IntrariLapteCalitativScriptic_Compartiment,
	IntrariLapteCalitativScriptic.Sofer AS IntrariLapteCalitativScriptic_Sofer,
	RTRIM(IntrariLapteCalitativScriptic.Ruta)+' '+LTRIM(ISNULL(RuteLiv.Denumire,'')) AS IntrariLapteCalitativScriptic_Ruta,
	RTRIM(IntrariLapteCalitativScriptic.Punct_achizitie)+' '+LTRIM(ISNULL(lm.Denumire,'')) AS IntrariLapteCalitativScriptic_Punct_achizitie,
	IntrariLapteCalitativScriptic.Aviz AS IntrariLapteCalitativScriptic_Aviz,
	IntrariLapteCalitativScriptic.Furnizor AS IntrariLapteCalitativScriptic_Furnizor,
	IntrariLapteCalitativScriptic.Cod AS IntrariLapteCalitativScriptic_Cod,
	RTRIM(IntrariLapteCalitativScriptic.Gestiune)+' '+LTRIM(ISNULL(gestiuni.Denumire_gestiune,'')) AS IntrariLapteCalitativScriptic_Gestiune,
	IntrariLapteCalitativScriptic.Cantitate AS IntrariLapteCalitativScriptic_Cantitate,
	IntrariLapteCalitativScriptic.gras_scriptic AS IntrariLapteCalitativScriptic_gras_scriptic,
	IntrariLapteCalitativScriptic.cant_UG_scriptic AS IntrariLapteCalitativScriptic_cant_UG_scriptic,
	IntrariLapteCalitativScriptic.subst_scriptic AS IntrariLapteCalitativScriptic_subst_scriptic,
	IntrariLapteCalitativScriptic.cant_US_scriptic AS IntrariLapteCalitativScriptic_cant_US_scriptic,
	IntrariLapteCalitativScriptic.dens_scriptic AS IntrariLapteCalitativScriptic_dens_scriptic,
	IntrariLapteCalitativScriptic.cant_UD_scriptic AS IntrariLapteCalitativScriptic_cant_UD_scriptic,
	IntrariLapteCalitativScriptic.apa_scriptic AS IntrariLapteCalitativScriptic_apa_scriptic,
	IntrariLapteCalitativScriptic.cant_UA_scriptic AS IntrariLapteCalitativScriptic_cant_UA_scriptic,
	IntrariLapteCalitativScriptic.prot_scriptic AS IntrariLapteCalitativScriptic_prot_scriptic,
	IntrariLapteCalitativScriptic.cant_UP_scriptic AS IntrariLapteCalitativScriptic_cant_UP_scriptic,
	IntrariLapteCalitativScriptic.Pret_valuta AS IntrariLapteCalitativScriptic_Pret_valuta,
	IntrariLapteCalitativScriptic.Pret_de_stoc AS IntrariLapteCalitativScriptic_Pret_de_stoc,
	IntrariLapteCalitativScriptic.Adaos AS IntrariLapteCalitativScriptic_Adaos,
	IntrariLapteCalitativScriptic.Pret_vanzare AS IntrariLapteCalitativScriptic_Pret_vanzare,
	IntrariLapteCalitativScriptic.Pret_cu_amanuntul AS IntrariLapteCalitativScriptic_Pret_cu_amanuntul,
	IntrariLapteCalitativScriptic.TVA_deductibil AS IntrariLapteCalitativScriptic_TVA_deductibil,
	IntrariLapteCalitativScriptic.Cota_TVA AS IntrariLapteCalitativScriptic_Cota_TVA,
	IntrariLapteCalitativScriptic.Utilizator AS IntrariLapteCalitativScriptic_Utilizator,
	IntrariLapteCalitativScriptic.Data_operarii AS IntrariLapteCalitativScriptic_Data_operarii,
	IntrariLapteCalitativScriptic.Ora_operarii AS IntrariLapteCalitativScriptic_Ora_operarii,
	IntrariLapteCalitativScriptic.Cod_intrare AS IntrariLapteCalitativScriptic_Cod_intrare,
	IntrariLapteCalitativScriptic.Cont_de_stoc AS IntrariLapteCalitativScriptic_Cont_de_stoc,
	IntrariLapteCalitativScriptic.Cont_corespondent AS IntrariLapteCalitativScriptic_Cont_corespondent,
	IntrariLapteCalitativScriptic.TVA_neexigibil AS IntrariLapteCalitativScriptic_TVA_neexigibil,
	IntrariLapteCalitativScriptic.Pret_amanunt_predator AS IntrariLapteCalitativScriptic_Pret_amanunt_predator,
	IntrariLapteCalitativScriptic.Tip_miscare AS IntrariLapteCalitativScriptic_Tip_miscare,
	IntrariLapteCalitativScriptic.Locatie AS IntrariLapteCalitativScriptic_Locatie,
	IntrariLapteCalitativScriptic.Data_expirarii AS IntrariLapteCalitativScriptic_Data_expirarii,
	IntrariLapteCalitativScriptic.Loc_de_munca AS IntrariLapteCalitativScriptic_Loc_de_munca,
	IntrariLapteCalitativScriptic.Comanda AS IntrariLapteCalitativScriptic_Comanda,
	IntrariLapteCalitativScriptic.Barcod AS IntrariLapteCalitativScriptic_Barcod,
	IntrariLapteCalitativScriptic.Cont_intermediar AS IntrariLapteCalitativScriptic_Cont_intermediar,
	IntrariLapteCalitativScriptic.Cont_venituri AS IntrariLapteCalitativScriptic_Cont_venituri,
	IntrariLapteCalitativScriptic.Discount AS IntrariLapteCalitativScriptic_Discount,
	IntrariLapteCalitativScriptic.Tert AS IntrariLapteCalitativScriptic_Tert,
	IntrariLapteCalitativScriptic.Factura AS IntrariLapteCalitativScriptic_Factura,
	IntrariLapteCalitativScriptic.Gestiune_primitoare AS IntrariLapteCalitativScriptic_Gestiune_primitoare,
	IntrariLapteCalitativScriptic.Numar_DVI AS IntrariLapteCalitativScriptic_Numar_DVI,
	IntrariLapteCalitativScriptic.Stare AS IntrariLapteCalitativScriptic_Stare,
	IntrariLapteCalitativScriptic.Grupa AS IntrariLapteCalitativScriptic_Grupa,
	IntrariLapteCalitativScriptic.Cont_factura AS IntrariLapteCalitativScriptic_Cont_factura,
	IntrariLapteCalitativScriptic.Valuta AS IntrariLapteCalitativScriptic_Valuta,
	IntrariLapteCalitativScriptic.Curs AS IntrariLapteCalitativScriptic_Curs,
	IntrariLapteCalitativScriptic.Data_facturii AS IntrariLapteCalitativScriptic_Data_facturii,
	IntrariLapteCalitativScriptic.Data_scadentei AS IntrariLapteCalitativScriptic_Data_scadentei,
	IntrariLapteCalitativScriptic.Procent_vama AS IntrariLapteCalitativScriptic_Procent_vama,
	IntrariLapteCalitativScriptic.Suprataxe_vama AS IntrariLapteCalitativScriptic_Suprataxe_vama,
	IntrariLapteCalitativScriptic.Accize_cumparare AS IntrariLapteCalitativScriptic_Accize_cumparare,
	IntrariLapteCalitativScriptic.Accize_datorate AS IntrariLapteCalitativScriptic_Accize_datorate,
	IntrariLapteCalitativScriptic.Contract AS IntrariLapteCalitativScriptic_Contract,
	IntrariLapteCalitativScriptic.Jurnal AS IntrariLapteCalitativScriptic_Jurnal,
	IntrariLapteCalitativScriptic.Cod_lapte AS IntrariLapteCalitativScriptic_Cod_lapte,
	IntrariLapteCalitativScriptic.Identificator AS IntrariLapteCalitativScriptic_Identificator,
	comenzi.Subunitate AS comenzi_Subunitate,
	comenzi.Comanda AS comenzi_Comanda,
	comenzi.Tip_comanda AS comenzi_Tip_comanda,
	comenzi.Descriere AS comenzi_Descriere,
	comenzi.Data_lansarii AS comenzi_Data_lansarii,
	comenzi.Data_inchiderii AS comenzi_Data_inchiderii,
	comenzi.Starea_comenzii AS comenzi_Starea_comenzii,
	comenzi.Grup_de_comenzi AS comenzi_Grup_de_comenzi,
	comenzi.Loc_de_munca AS comenzi_Loc_de_munca,
	comenzi.Numar_de_inventar AS comenzi_Numar_de_inventar,
	comenzi.Beneficiar AS comenzi_Beneficiar,
	comenzi.Loc_de_munca_beneficiar AS comenzi_Loc_de_munca_beneficiar,
	comenzi.Comanda_beneficiar AS comenzi_Comanda_beneficiar,
	comenzi.Art_calc_benef AS comenzi_Art_calc_benef,
	CalStd.Data AS CalStd_Data,
	CalStd.Data_lunii AS CalStd_Data_lunii,
	CalStd.An AS CalStd_An,
	CalStd.Luna AS CalStd_Luna,
	CalStd.LunaAlfa AS CalStd_LunaAlfa,
	CalStd.Zi AS CalStd_Zi,
	CalStd.Saptamana AS CalStd_Saptamana,
	CalStd.Trimestru AS CalStd_Trimestru,
	CalStd.Zi_alfa AS CalStd_Zi_alfa,
	CalStd.Camp1 AS CalStd_Camp1,
	CalStd.Camp2 AS CalStd_Camp2,
	CalStd.Camp3 AS CalStd_Camp3,
	CalStd.Fel_zi AS CalStd_Fel_zi,
	RuteLiv.Cod AS RuteLiv_Cod,
	RuteLiv.Denumire AS RuteLiv_Denumire,
	RuteLiv.Schimb AS RuteLiv_Schimb,
	RuteLiv.Delegat AS RuteLiv_Delegat,
	RuteLiv.numarul_mijlocului AS RuteLiv_numarul_mijlocului,
	RuteLiv.Serie_buletin AS RuteLiv_Serie_buletin,
	RuteLiv.Numar_Buletin AS RuteLiv_Numar_Buletin,
	RuteLiv.Eliberat AS RuteLiv_Eliberat,
	nomencl.Cod AS nomencl_Cod,
	nomencl.Tip AS nomencl_Tip,
	nomencl.Denumire AS nomencl_Denumire,
	nomencl.UM AS nomencl_UM,
	nomencl.UM_1 AS nomencl_UM_1,
	nomencl.Coeficient_conversie_1 AS nomencl_Coeficient_conversie_1,
	nomencl.UM_2 AS nomencl_UM_2,
	nomencl.Coeficient_conversie_2 AS nomencl_Coeficient_conversie_2,
	nomencl.Cont AS nomencl_Cont,
	nomencl.Grupa AS nomencl_Grupa,
	nomencl.Valuta AS nomencl_Valuta,
	nomencl.Pret_in_valuta AS nomencl_Pret_in_valuta,
	nomencl.Pret_stoc AS nomencl_Pret_stoc,
	nomencl.Pret_vanzare AS nomencl_Pret_vanzare,
	nomencl.Pret_cu_amanuntul AS nomencl_Pret_cu_amanuntul,
	nomencl.Cota_TVA AS nomencl_Cota_TVA,
	nomencl.Stoc_limita AS nomencl_Stoc_limita,
	nomencl.Stoc AS nomencl_Stoc,
	nomencl.Greutate_specifica AS nomencl_Greutate_specifica,
	nomencl.Furnizor AS nomencl_Furnizor,
	nomencl.Loc_de_munca AS nomencl_Loc_de_munca,
	nomencl.Gestiune AS nomencl_Gestiune,
	nomencl.Categorie AS nomencl_Categorie,
	nomencl.Tip_echipament AS nomencl_Tip_echipament,
	gestiuni.Subunitate AS gestiuni_Subunitate,
	gestiuni.Tip_gestiune AS gestiuni_Tip_gestiune,
	gestiuni.Cod_gestiune AS gestiuni_Cod_gestiune,
	gestiuni.Denumire_gestiune AS gestiuni_Denumire_gestiune,
	gestiuni.Cont_contabil_specific AS gestiuni_Cont_contabil_specific,
	terti.Subunitate AS terti_Subunitate,
	terti.Tert AS terti_Tert,
	terti.Denumire AS terti_Denumire,
	terti.Cod_fiscal AS terti_Cod_fiscal,
	terti.Localitate AS terti_Localitate,
	terti.Judet AS terti_Judet,
	terti.Adresa AS terti_Adresa,
	terti.Telefon_fax AS terti_Telefon_fax,
	terti.Banca AS terti_Banca,
	terti.Cont_in_banca AS terti_Cont_in_banca,
	terti.Tert_extern AS terti_Tert_extern,
	terti.Grupa AS terti_Grupa,
	terti.Cont_ca_furnizor AS terti_Cont_ca_furnizor,
	terti.Cont_ca_beneficiar AS terti_Cont_ca_beneficiar,
	terti.Sold_ca_furnizor AS terti_Sold_ca_furnizor,
	terti.Sold_ca_beneficiar AS terti_Sold_ca_beneficiar,
	terti.Sold_maxim_ca_beneficiar AS terti_Sold_maxim_ca_beneficiar,
	terti.Disccount_acordat AS terti_Disccount_acordat,
	lm.Nivel AS lm_Nivel,
	lm.Cod AS lm_Cod,
	lm.Cod_parinte AS lm_Cod_parinte,
	lm.Denumire AS lm_Denumire
	
/*
select 
rtrim(t.name)
--'IntrariLapteComp'
+'.'+rtrim(ltrim(c.name))+' AS '
+rtrim(t.name)
--+'IntrariLapteComp'
+'_'+rtrim(ltrim(c.name))+','
from sysobjects t 
	inner join syscolumns c on t.id=c.id
where t.name='IntrariLapteCalitativScriptic'
*/
FROM IntrariLapteCalitativScriptic
/*	LEFT JOIN IntrariLapteFapticGrupatPeTureSiCompartimente IntrariLapteComp 
		on IntrariLapteComp.subunitate= IntrariLapte.subunitate and IntrariLapteComp.data= IntrariLapte.data
			and IntrariLapteComp.comanda= IntrariLapte.comanda and IntrariLapteComp.tura= IntrariLapte.tura
			and IntrariLapteComp.cod= IntrariLapte.cod and IntrariLapteComp.compartiment= IntrariLapte.compartiment*/
	LEFT JOIN comenzi on comenzi.subunitate= IntrariLapteCalitativScriptic.subunitate 
		and comenzi.comanda= IntrariLapteCalitativScriptic.Masina
	LEFT JOIN calstd on calstd.data=IntrariLapteCalitativScriptic.data
	LEFT JOIN RuteLiv on IntrariLapteCalitativScriptic.ruta=RuteLIv.cod
	LEFT JOIN nomencl on nomencl.cod=IntrariLapteCalitativScriptic.tip_lapte
	LEFT JOIN terti on terti.subunitate= IntrariLapteCalitativScriptic.subunitate and terti.tert= IntrariLapteCalitativScriptic.tert
	LEFT JOIN gestiuni on gestiuni.subunitate= IntrariLapteCalitativScriptic.subunitate and gestiuni.cod_gestiune= IntrariLapteCalitativScriptic.gestiune
	LEFT JOIN lm on IntrariLapteCalitativScriptic.Punct_achizitie=lm.cod

