CREATE
VIEW [dbo].[CG_pozdoc] AS
SELECT 
pozdoc.Subunitate AS pozdoc_Subunitate,
pozdoc.Tip AS pozdoc_Tip,
pozdoc.Numar AS pozdoc_Numar,
RTRIM(pozdoc.Cod)+' '+RTRIM(ISNULL(nomencl.Denumire,'')) AS pozdoc_Cod,
pozdoc.Data AS pozdoc_Data,
RTRIM(pozdoc.Gestiune)+' '+RTRIM(ISNULL(gestiuni.Denumire_gestiune,'')) AS pozdoc_Gestiune,
pozdoc.Cantitate AS pozdoc_Cantitate,
pozdoc.Pret_valuta AS pozdoc_Pret_valuta,
pozdoc.Pret_de_stoc AS pozdoc_Pret_de_stoc,
pozdoc.Adaos AS pozdoc_Adaos,
pozdoc.Pret_vanzare AS pozdoc_Pret_vanzare,
pozdoc.Pret_cu_amanuntul AS pozdoc_Pret_cu_amanuntul,
pozdoc.TVA_deductibil AS pozdoc_TVA_deductibil,
pozdoc.Cota_TVA AS pozdoc_Cota_TVA,
pozdoc.Utilizator AS pozdoc_Utilizator,
pozdoc.Data_operarii AS pozdoc_Data_operarii,
pozdoc.Ora_operarii AS pozdoc_Ora_operarii,
pozdoc.Cod_intrare AS pozdoc_Cod_intrare,
pozdoc.Cont_de_stoc AS pozdoc_Cont_de_stoc,
pozdoc.Cont_corespondent AS pozdoc_Cont_corespondent,
pozdoc.TVA_neexigibil AS pozdoc_TVA_neexigibil,
pozdoc.Pret_amanunt_predator AS pozdoc_Pret_amanunt_predator,
pozdoc.Tip_miscare AS pozdoc_Tip_miscare,
pozdoc.Locatie AS pozdoc_Locatie,
pozdoc.Data_expirarii AS pozdoc_Data_expirarii,
pozdoc.Numar_pozitie AS pozdoc_Numar_pozitie,
RTRIM(pozdoc.Loc_de_munca)+' '+RTRIM(ISNULL(lm.Denumire,'')) AS pozdoc_Loc_de_munca,
RTRIM(pozdoc.Comanda)+' '+RTRIM(ISNULL(comenzi.Descriere,'')) AS pozdoc_Comanda,
pozdoc.Barcod AS pozdoc_Barcod,
pozdoc.Cont_intermediar AS pozdoc_Cont_intermediar,
pozdoc.Cont_venituri AS pozdoc_Cont_venituri,
pozdoc.Discount AS pozdoc_Discount,
pozdoc.Tert AS pozdoc_Tert,
pozdoc.Factura AS pozdoc_Factura,
pozdoc.Gestiune_primitoare AS pozdoc_Gestiune_primitoare,
pozdoc.Numar_DVI AS pozdoc_Numar_DVI,
pozdoc.Stare AS pozdoc_Stare,
pozdoc.Grupa AS pozdoc_Grupa,
pozdoc.Cont_factura AS pozdoc_Cont_factura,
pozdoc.Valuta AS pozdoc_Valuta,
pozdoc.Curs AS pozdoc_Curs,
pozdoc.Data_facturii AS pozdoc_Data_facturii,
pozdoc.Data_scadentei AS pozdoc_Data_scadentei,
pozdoc.Procent_vama AS pozdoc_Procent_vama,
pozdoc.Suprataxe_vama AS pozdoc_Suprataxe_vama,
pozdoc.Accize_cumparare AS pozdoc_Accize_cumparare,
pozdoc.Accize_datorate AS pozdoc_Accize_datorate,
pozdoc.Contract AS pozdoc_Contract,
pozdoc.Jurnal AS pozdoc_Jurnal,
CalStd.Data AS CalStd_Data,
CalStd.Data_lunii AS CalStd_Data_lunii,
CalStd.An AS CalStd_An,
CalStd.Luna AS CalStd_Luna,
CalStd.LunaAlfa AS CalStd_LunaAlfa,
CalStd.Zi AS CalStd_Zi,
CalStd.Saptamana AS CalStd_Saptamana,
CalStd.Trimestru AS CalStd_Trimestru,
CalStd.Zi_alfa AS CalStd_Zi_alfa,
CalStd.Camp1 AS CalStd_Camp1,
CalStd.Camp2 AS CalStd_Camp2,
CalStd.Camp3 AS CalStd_Camp3,
CalStd.Fel_zi AS CalStd_Fel_zi,
nomencl.Cod AS nomencl_Cod,
nomencl.Tip AS nomencl_Tip,
nomencl.Denumire AS nomencl_Denumire,
nomencl.UM AS nomencl_UM,
nomencl.UM_1 AS nomencl_UM_1,
nomencl.Coeficient_conversie_1 AS nomencl_Coeficient_conversie_1,
nomencl.UM_2 AS nomencl_UM_2,
nomencl.Coeficient_conversie_2 AS nomencl_Coeficient_conversie_2,
nomencl.Cont AS nomencl_Cont,
nomencl.Grupa AS nomencl_Grupa,
nomencl.Valuta AS nomencl_Valuta,
nomencl.Pret_in_valuta AS nomencl_Pret_in_valuta,
nomencl.Pret_stoc AS nomencl_Pret_stoc,
nomencl.Pret_vanzare AS nomencl_Pret_vanzare,
nomencl.Pret_cu_amanuntul AS nomencl_Pret_cu_amanuntul,
nomencl.Cota_TVA AS nomencl_Cota_TVA,
nomencl.Stoc_limita AS nomencl_Stoc_limita,
nomencl.Stoc AS nomencl_Stoc,
nomencl.Greutate_specifica AS nomencl_Greutate_specifica,
nomencl.Furnizor AS nomencl_Furnizor,
nomencl.Loc_de_munca AS nomencl_Loc_de_munca,
nomencl.Gestiune AS nomencl_Gestiune,
nomencl.Categorie AS nomencl_Categorie,
nomencl.Tip_echipament AS nomencl_Tip_echipament,
gestiuni.Subunitate AS gestiuni_Subunitate,
gestiuni.Tip_gestiune AS gestiuni_Tip_gestiune,
gestiuni.Cod_gestiune AS gestiuni_Cod_gestiune,
gestiuni.Denumire_gestiune AS gestiuni_Denumire_gestiune,
gestiuni.Cont_contabil_specific AS gestiuni_Cont_contabil_specific,
lm.Nivel AS lm_Nivel,
lm.Cod AS lm_Cod,
lm.Cod_parinte AS lm_Cod_parinte,
lm.Denumire AS lm_Denumire,
comenzi.Subunitate AS comenzi_Subunitate,
comenzi.Comanda AS comenzi_Comanda,
comenzi.Tip_comanda AS comenzi_Tip_comanda,
comenzi.Descriere AS comenzi_Descriere,
comenzi.Data_lansarii AS comenzi_Data_lansarii,
comenzi.Data_inchiderii AS comenzi_Data_inchiderii,
comenzi.Starea_comenzii AS comenzi_Starea_comenzii,
comenzi.Grup_de_comenzi AS comenzi_Grup_de_comenzi,
comenzi.Loc_de_munca AS comenzi_Loc_de_munca,
comenzi.Numar_de_inventar AS comenzi_Numar_de_inventar,
comenzi.Beneficiar AS comenzi_Beneficiar,
comenzi.Loc_de_munca_beneficiar AS comenzi_Loc_de_munca_beneficiar,
comenzi.Comanda_beneficiar AS comenzi_Comanda_beneficiar,
comenzi.Art_calc_benef AS comenzi_Art_calc_benef,
(SELECT TOP 1 pozcom.Cantitate FROM pozcom WHERE pozcom.Subunitate= comenzi.Subunitate AND pozcom.Comanda= comenzi.Comanda ORDER BY pozcom.Cod_produs) AS pozcom_Cantitate,
(SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda) AS pozcom_Cod_produs,
grcom.Tip_comanda AS grcom_Tip_comanda,
RTRIM((SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda))+' '+
RTRIM(grcom.Grupa) AS grcom_Grupa,
grcom.Denumire_grupa AS grcom_Denumire_grupa
FROM pozdoc
	LEFT JOIN CalStd ON pozdoc.data= CalStd.Data
	LEFT JOIN nomencl ON pozdoc.cod= nomencl.cod
	LEFT JOIN gestiuni ON pozdoc.subunitate= gestiuni.subunitate AND pozdoc.Gestiune= gestiuni.Cod_gestiune
	LEFT JOIN lm ON pozdoc.Loc_de_munca= lm.cod
	LEFT JOIN comenzi ON pozdoc.subunitate= comenzi.subunitate AND pozdoc.comanda= comenzi.comanda
	LEFT JOIN grcom ON grcom.Tip_comanda= comenzi.Tip_comanda 
		AND grcom.Grupa= (SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda)
