CREATE
-- ALTER
VIEW [dbo].[MF_fisamf] AS
SELECT
fisaMF.Subunitate AS fisaMF_Subunitate,
RTRIM(fisaMF.Numar_de_inventar)+' '+RTRIM(ISNULL(Mfix.Denumire,'')) AS fisaMF_Numar_de_inventar,
fisaMF.Categoria AS fisaMF_Categoria,
fisaMF.Data_lunii_operatiei AS fisaMF_Data_lunii_operatiei,
fisaMF.Felul_operatiei AS fisaMF_Felul_operatiei,
RTRIM(fisaMF.Loc_de_munca)+' '+RTRIM(ISNULL(lm.Denumire,'')) AS fisaMF_Loc_de_munca,
fisaMF.Gestiune AS fisaMF_Gestiune,
RTRIM(fisaMF.Comanda)+' '+RTRIM(ISNULL(comenzi.Descriere,'')) AS fisaMF_Comanda,
fisaMF.Valoare_de_inventar AS fisaMF_Valoare_de_inventar,
fisaMF.Valoare_amortizata AS fisaMF_Valoare_amortizata,
fisaMF.Valoare_amortizata_cont_8045 AS fisaMF_Valoare_amortizata_cont_8045,
fisaMF.Valoare_amortizata_cont_6871 AS fisaMF_Valoare_amortizata_cont_6871,
fisaMF.Amortizare_lunara AS fisaMF_Amortizare_lunara,
fisaMF.Amortizare_lunara_cont_8045 AS fisaMF_Amortizare_lunara_cont_8045,
fisaMF.Amortizare_lunara_cont_6871 AS fisaMF_Amortizare_lunara_cont_6871,
fisaMF.Durata AS fisaMF_Durata,
fisaMF.Obiect_de_inventar AS fisaMF_Obiect_de_inventar,
fisaMF.Cont_mijloc_fix AS fisaMF_Cont_mijloc_fix,
fisaMF.Numar_de_luni_pana_la_am_int AS fisaMF_Numar_de_luni_pana_la_am_int,
fisaMF.Cantitate AS fisaMF_Cantitate,
MFix.Subunitate AS MFix_Subunitate,
MFix.Numar_de_inventar AS MFix_Numar_de_inventar,
MFix.Denumire AS MFix_Denumire,
MFix.Serie AS MFix_Serie,
MFix.Tip_amortizare AS MFix_Tip_amortizare,
MFix.Cod_de_clasificare AS MFix_Cod_de_clasificare,
MFix.Data_punerii_in_functiune AS MFix_Data_punerii_in_functiune,
CalStd.Data AS CalStd_Data,
CalStd.Data_lunii AS CalStd_Data_lunii,
CalStd.An AS CalStd_An,
CalStd.Luna AS CalStd_Luna,
CalStd.LunaAlfa AS CalStd_LunaAlfa,
CalStd.Zi AS CalStd_Zi,
CalStd.Saptamana AS CalStd_Saptamana,
CalStd.Trimestru AS CalStd_Trimestru,
CalStd.Zi_alfa AS CalStd_Zi_alfa,
CalStd.Camp1 AS CalStd_Camp1,
CalStd.Camp2 AS CalStd_Camp2,
CalStd.Camp3 AS CalStd_Camp3,
CalStd.Fel_zi AS CalStd_Fel_zi,
lm.Nivel AS lm_Nivel,
lm.Cod AS lm_Cod,
lm.Cod_parinte AS lm_Cod_parinte,
lm.Denumire AS lm_Denumire,
gestiuni.Subunitate AS gestiuni_Subunitate,
gestiuni.Tip_gestiune AS gestiuni_Tip_gestiune,
gestiuni.Cod_gestiune AS gestiuni_Cod_gestiune,
gestiuni.Denumire_gestiune AS gestiuni_Denumire_gestiune,
gestiuni.Cont_contabil_specific AS gestiuni_Cont_contabil_specific,
comenzi.Subunitate AS comenzi_Subunitate,
comenzi.Comanda AS comenzi_Comanda,
comenzi.Tip_comanda AS comenzi_Tip_comanda,
comenzi.Descriere AS comenzi_Descriere,
comenzi.Data_lansarii AS comenzi_Data_lansarii,
comenzi.Data_inchiderii AS comenzi_Data_inchiderii,
comenzi.Starea_comenzii AS comenzi_Starea_comenzii,
comenzi.Grup_de_comenzi AS comenzi_Grup_de_comenzi,
comenzi.Loc_de_munca AS comenzi_Loc_de_munca,
comenzi.Numar_de_inventar AS comenzi_Numar_de_inventar,
comenzi.Beneficiar AS comenzi_Beneficiar,
comenzi.Loc_de_munca_beneficiar AS comenzi_Loc_de_munca_beneficiar,
comenzi.Comanda_beneficiar AS comenzi_Comanda_beneficiar,
comenzi.Art_calc_benef AS comenzi_Art_calc_benef,
(SELECT TOP 1 pozcom.Cantitate FROM pozcom WHERE pozcom.Subunitate= comenzi.Subunitate AND pozcom.Comanda= comenzi.Comanda ORDER BY pozcom.Cod_produs) AS pozcom_Cantitate,
(SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda) AS pozcom_Cod_produs,
grcom.Tip_comanda AS grcom_Tip_comanda,
RTRIM((SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda))+' '+
RTRIM(grcom.Grupa) AS grcom_Grupa,
grcom.Denumire_grupa AS grcom_Denumire_grupa
FROM fisamf
	LEFT JOIN mfix ON fisaMF.Subunitate= mfix.Subunitate AND fisaMF.Numar_de_inventar= mfix.Numar_de_inventar
	LEFT JOIN CalStd ON fisaMF.Data_lunii_operatiei= CalStd.Data
	LEFT JOIN lm ON fisamf.Loc_de_munca= lm.cod
	LEFT JOIN gestiuni ON fisamf.subunitate= gestiuni.subunitate AND fisamf.gestiune= gestiuni.cod_gestiune
	LEFT JOIN comenzi ON fisamf.subunitate= comenzi.subunitate AND fisamf.comanda= comenzi.comanda
	LEFT JOIN grcom ON grcom.Tip_comanda= comenzi.Tip_comanda 
		AND grcom.Grupa= (SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda)
