CREATE
VIEW [dbo].[MM_elementemasini] AS
SELECT
elemtipm.Tip_masina AS elemtipm_Tip_masina,
elemtipm.Element AS elemtipm_Element,
elemtipm.Mod_calcul AS elemtipm_Mod_calcul,
elemtipm.Formula AS elemtipm_Formula,
elemtipm.Valoare AS elemtipm_Valoare,
elemtipm.Ord_macheta AS elemtipm_Ord_macheta,
elemtipm.Ord_raport AS elemtipm_Ord_raport,
elemtipm.Cu_totaluri AS elemtipm_Cu_totaluri,
elemtipm.Grupa AS elemtipm_Grupa,
tipmasini.Cod AS tipmasini_Cod,
tipmasini.Denumire AS tipmasini_Denumire,
tipmasini.Tip_activitate AS tipmasini_Tip_activitate,
elemente.Cod AS elemente_Cod,
elemente.Denumire AS elemente_Denumire,
elemente.Tip AS elemente_Tip,
elemente.UM AS elemente_UM,
elemente.UM2 AS elemente_UM2,
elemente.Interval AS elemente_Interval,
masini.cod_masina AS masini_cod_masina,
masini.tip_masina AS masini_tip_masina,
masini.nr_inmatriculare AS masini_nr_inmatriculare,
masini.denumire AS masini_denumire,
masini.nr_inventar AS masini_nr_inventar,
masini.capacitate_metri_cubi AS masini_capacitate_metri_cubi,
masini.consum_normat_100km AS masini_consum_normat_100km,
masini.consum_pe_ora AS masini_consum_pe_ora,
masini.grupa AS masini_grupa,
masini.loc_de_munca AS masini_loc_de_munca,
masini.coeficient AS masini_coeficient,
masini.tonaj AS masini_tonaj,
masini.benzina_sau_motorina AS masini_benzina_sau_motorina,
masini.capacitate_rezervor AS masini_capacitate_rezervor,
masini.capacitate_baie_de_ulei AS masini_capacitate_baie_de_ulei,
masini.norma_de_ulei AS masini_norma_de_ulei,
masini.consum_vara AS masini_consum_vara,
masini.consum_iarna AS masini_consum_iarna,
masini.consum_usor AS masini_consum_usor,
masini.consum_mediu AS masini_consum_mediu,
masini.consum_greu AS masini_consum_greu,
masini.km_la_bord_efectivi AS masini_km_la_bord_efectivi,
masini.km_la_bord_echivalenti AS masini_km_la_bord_echivalenti,
masini.km_SU AS masini_km_SU,
masini.km_RK AS masini_km_RK,
masini.km_RT1 AS masini_km_RT1,
masini.km_RT2 AS masini_km_RT2,
masini.ultim_SU AS masini_ultim_SU,
masini.ultim_RK AS masini_ultim_RK,
masini.ultim_RT1 AS masini_ultim_RT1,
masini.ultim_RT2 AS masini_ultim_RT2,
masini.de_care_masina AS masini_de_care_masina,
masini.de_putere_mare AS masini_de_putere_mare,
masini.Comanda AS masini_Comanda,
masini.data_expirarii_ITP AS masini_data_expirarii_ITP,
masini.Firma_CASCO AS masini_Firma_CASCO,
masini.Serie_caroserie AS masini_Serie_caroserie,
ISNULL(coefmasini.Masina, masini.cod_masina) AS coefmasini_Masina,
ISNULL(coefmasini.Coeficient, elemtipm.element) AS coefmasini_Coeficient,
ISNULL(coefmasini.Valoare, elemtipm.Valoare) AS coefmasini_Valoare,
coefmasini.Interval AS coefmasini_Interval,
comenzi.Subunitate AS comenzi_Subunitate,
comenzi.Comanda AS comenzi_Comanda,
comenzi.Tip_comanda AS comenzi_Tip_comanda,
comenzi.Descriere AS comenzi_Descriere,
comenzi.Data_lansarii AS comenzi_Data_lansarii,
comenzi.Data_inchiderii AS comenzi_Data_inchiderii,
comenzi.Starea_comenzii AS comenzi_Starea_comenzii,
comenzi.Grup_de_comenzi AS comenzi_Grup_de_comenzi,
comenzi.Loc_de_munca AS comenzi_Loc_de_munca,
comenzi.Numar_de_inventar AS comenzi_Numar_de_inventar,
comenzi.Beneficiar AS comenzi_Beneficiar,
comenzi.Loc_de_munca_beneficiar AS comenzi_Loc_de_munca_beneficiar,
comenzi.Comanda_beneficiar AS comenzi_Comanda_beneficiar,
comenzi.Art_calc_benef AS comenzi_Art_calc_benef,
(SELECT TOP 1 pozcom.Cantitate FROM pozcom WHERE pozcom.Subunitate= comenzi.Subunitate AND pozcom.Comanda= comenzi.Comanda ORDER BY pozcom.Cod_produs) AS pozcom_Cantitate,
(SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda) AS pozcom_Cod_produs,
grcom.Tip_comanda AS grcom_Tip_comanda,
RTRIM((SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda))+' '+
RTRIM(grcom.Grupa) AS grcom_Grupa,
grcom.Denumire_grupa AS grcom_Denumire_grupa
FROM elemtipm
	LEFT JOIN tipmasini ON tipmasini.cod= elemtipm.Tip_masina
	LEFT JOIN elemente ON elemente.cod= elemtipm.element
	LEFT JOIN masini ON masini.Tip_masina= elemtipm.Tip_masina
	LEFT JOIN coefmasini ON coefmasini.masina= masini.cod_masina AND coefmasini.coeficient= elemtipm.element
	LEFT JOIN comenzi ON masini.comanda= comenzi.comanda AND comenzi.subunitate='1'
	LEFT JOIN grcom ON grcom.Tip_comanda= comenzi.Tip_comanda 
		AND grcom.Grupa= (SELECT MIN(pozcom.Cod_produs) FROM pozcom WHERE pozcom.Subunitate= 'GR' AND pozcom.Comanda= comenzi.Comanda)
