

CREATE VIEW [dbo].[Situatie_ReceptieIntrariLapteCalitativScriptic] AS
select
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Data_cursa AS Data_cursa,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Masina AS Masina,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Tura AS Tura,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Tip_lapte AS Tip_lapte,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Compartiment AS Compartiment,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Gestiune AS Gestiune,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Aviz AS Aviz,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Punct_achizitie AS Punct_achizitie,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Sofer AS Sofer,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Ruta AS Ruta,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Furnizor AS Furnizor,

CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Tip AS Tip,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Numar AS Numar,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Factura AS Factura,

CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Cantitate AS Cantitate,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_Pret_de_stoc AS Pret_de_stoc,

CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_cantitate AS cant_UM_scriptic,

CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_gras_scriptic AS gras_scriptic,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_cant_UG_scriptic AS cant_UG_scriptic,

CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_subst_scriptic AS subst_scriptic,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_cant_US_scriptic AS cant_US_scriptic,

CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_dens_scriptic AS dens_scriptic,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_cant_UD_scriptic AS cant_UD_scriptic,

CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_apa_scriptic AS apa_scriptic,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_cant_UA_scriptic AS cant_UA_scriptic,

CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_prot_scriptic AS prot_scriptic,
CG_IntrariLapteCalitativScriptic.IntrariLapteCalitativScriptic_cant_UP_scriptic AS cant_UP_scriptic,

CG_IntrariLapteCalitativScriptic.CalStd_Data,
CG_IntrariLapteCalitativScriptic.CalStd_Data_lunii AS Data_lunii,
CG_IntrariLapteCalitativScriptic.CalStd_An AS An,
CG_IntrariLapteCalitativScriptic.CalStd_Luna AS Luna,
CG_IntrariLapteCalitativScriptic.CalStd_LunaAlfa AS LunaAlfa,
CG_IntrariLapteCalitativScriptic.CalStd_Zi AS Zi,
CG_IntrariLapteCalitativScriptic.CalStd_Zi_alfa AS Zi_alfa,

CG_IntrariLapteCalitativScriptic.comenzi_Comanda,
CG_IntrariLapteCalitativScriptic.comenzi_Tip_comanda AS Tip_comanda,
CG_IntrariLapteCalitativScriptic.comenzi_Descriere,

CG_IntrariLapteCalitativScriptic.RuteLiv_Cod,
CG_IntrariLapteCalitativScriptic.RuteLiv_Denumire,
CG_IntrariLapteCalitativScriptic.RuteLiv_Schimb,

CG_IntrariLapteCalitativScriptic.nomencl_Cod,
CG_IntrariLapteCalitativScriptic.nomencl_Tip,
CG_IntrariLapteCalitativScriptic.nomencl_Denumire,
CG_IntrariLapteCalitativScriptic.nomencl_UM,
CG_IntrariLapteCalitativScriptic.nomencl_UM_1,
CG_IntrariLapteCalitativScriptic.nomencl_Coeficient_conversie_1,
CG_IntrariLapteCalitativScriptic.nomencl_UM_2,
CG_IntrariLapteCalitativScriptic.nomencl_Coeficient_conversie_2,
CG_IntrariLapteCalitativScriptic.nomencl_Grupa,

CG_IntrariLapteCalitativScriptic.gestiuni_Tip_gestiune AS Tip_gestiune,
CG_IntrariLapteCalitativScriptic.gestiuni_Cod_gestiune AS Cod_gestiune,
CG_IntrariLapteCalitativScriptic.gestiuni_Denumire_gestiune AS Denumire_gestiune,

CG_IntrariLapteCalitativScriptic.lm_Nivel,
CG_IntrariLapteCalitativScriptic.lm_Cod,

CG_IntrariLapteCalitativScriptic.terti_Tert,
CG_IntrariLapteCalitativScriptic.terti_Denumire,
CG_IntrariLapteCalitativScriptic.terti_Cod_fiscal,
CG_IntrariLapteCalitativScriptic.terti_Localitate,
CG_IntrariLapteCalitativScriptic.terti_Judet,
CG_IntrariLapteCalitativScriptic.terti_Adresa

/*
select rtrim(t.name)+'.'+rtrim(ltrim(c.name))
--+' AS '+rtrim(t.name)+'_'+rtrim(ltrim(c.name))
+','
from sysobjects t 
	inner join syscolumns c on t.id=c.id
where t.name='CG_IntrariLapteCalitativScripticCompartimente'
*/
FROM CG_IntrariLapteCalitativScriptic

