CREATE VIEW [Situatie_AdeverinteSubventiiLapte] AS
SELECT     
AdevLapteSubventionat_Nr_inregistrare AS Nr_inregistrare, 
AdevLapteSubventionat_Data AS Data, 
AdevLapteSubventionat_Centru_colectare AS Centru_colectare,
CentrColectLapte_Loc_de_munca AS Loc_de_munca,
JudRegDACLapte_Regiune AS Regiune,
CentrColectLapte_Denumire,
ISNULL(NULLIF(JudRegDACLapte_Laborator_analize,''), p2.Val_alfanumerica) AS Laborator_analize,
ISNULL(NULLIF(JudRegDACLapte_Sediu_laborator,''), p3.Val_alfanumerica) AS Sediu_laborator,
AdevLapteSubventionat_Data_inf_livrare AS Data_inf_livrare,
AdevLapteSubventionat_Data_sup_livrare AS Data_sup_livrare,
AdevLapteSubventionat_Suma_cant_UM_livrata AS Suma_cant_UM_livrata, 
AdevLapteSubventionat_Suma_cant_UM_cota_livrata AS Suma_cant_UM_cota_livrata, 
AdevLapteSubventionat_Suma_cant_UM_subventionata AS Suma_cant_UM_subventionata, 
AdevLapteSubventionat_Suma_cant_UM_cota_subventionata AS Suma_cant_UM_cota_subventionata, 
AdevLapteSubventionat_Nr_luni_valide AS Nr_luni_valide, 
AdevLapteSubventionat_Buletine_analiza AS Buletine_analiza, 
AdevLapteSubventionat_Laboratoare_analize AS Laboratoare_analize,
AdevSubvenLapte_Producator AS Producator, 
AdevSubvenLapte_Data_inf_perioada AS Data_inf_perioada, 
AdevSubvenLapte_Data_sup_perioada AS Data_sup_perioada, 
Perioada_subventionata,
AdevSubvenLapte_Rezultat_trimestru AS Rezultat_trimestru, 
AdevSubvenLapte_Cantitate_livrata AS Cantitate_livrata, 
AdevSubvenLapte_Cantitate_livrata/ISNULL(NULLIF(p1.Val_numerica,0),1.03) AS Cant_UM_livrata, 
AdevSubvenLapte_Cantitate_subventionata AS Cantitate_subventionata, 
AdevSubvenLapte_Cantitate_subventionata/ISNULL(NULLIF(p1.Val_numerica,0),1.03) AS Cant_UM_subventionata, 
ProdLapte_Cod_producator AS Cod_producator, 
ProdLapte_Denumire, 
ProdLapte_Initiala_tatalui AS Initiala_tatalui, 
ProdLapte_Serie_buletin AS Serie_buletin, 
ProdLapte_Nr_buletin AS Nr_buletin, 
ProdLapte_Eliberat AS Eliberat, 
ProdLapte_CNP_CUI AS CNP_CUI, 
ProdLapte_Judet AS Judet, 
ProdLapte_Localitate AS Localitate, 
ProdLapte_Comuna AS Comuna, 
ProdLapte_Sat AS Sat, 
ProdLapte_Strada AS Strada, 
ProdLapte_Nr_str AS Nr_str, 
ProdLapte_Nr_casa AS Nr_casa, 
ProdLapte_Bloc AS Bloc, 
ProdLapte_Scara AS Scara, 
ProdLapte_Etaj AS Etaj, 
ProdLapte_Ap AS Ap, 
ProdLapte_Cod_exploatatie AS Cod_exploatatie, 
ProdLapte_Cota_actuala AS Cota_actuala, 
ProdLapte_Grad_actual AS Grad_actual, 
ProdLapte_Tip_pers AS Tip_pers, 
ProdLapte_Reprezentant AS Reprezentant, 
ProdLapte_CNP_repr AS CNP_repr, 
ReprProdLapte_Initiala_tatalui,
ReprProdLapte_Serie_buletin,
ReprProdLapte_Nr_buletin,
ReprProdLapte_Eliberat,
ReprProdLapte_CNP_CUI,
ReprProdLapte_Judet,
ReprProdLapte_Localitate,
ReprProdLapte_Comuna,
ReprProdLapte_Sat,
ReprProdLapte_Strada,
ReprProdLapte_Nr_str,
ReprProdLapte_Nr_casa,
ReprProdLapte_Bloc,
ReprProdLapte_Scara,
ReprProdLapte_Etaj,
ReprProdLapte_Ap,
ReprProdLapte_Cod_exploatatie,

Judete_denumire, 
Localitati_oras,
lm_Denumire
FROM AL_AdevLapteSubventionat
	LEFT JOIN par p1 on p1.tip_parametru= 'AL' and p1.parametru= 'COEFCONVL'
	LEFT JOIN par p2 on p2.tip_parametru= 'AL' and p2.parametru= 'LABANALIZ'
	LEFT JOIN par p3 on p3.tip_parametru= 'AL' and p3.parametru= 'SEDIULAB'