CREATE TABLE [dbo].[CMDCLA17] (
    [CAS_ANG]    CHAR (2)   NOT NULL,
    [TIPD]       SMALLINT   NOT NULL,
    [LN]         SMALLINT   NOT NULL,
    [AN]         SMALLINT   NOT NULL,
    [DEN_ANG]    CHAR (50)  NOT NULL,
    [CUI]        CHAR (13)  NOT NULL,
    [REG_COM]    CHAR (20)  NOT NULL,
    [NR_ANGAJ]   INT        NOT NULL,
    [TOT_SAL_BR] FLOAT (53) NOT NULL,
    [TOT_CONTRI] FLOAT (53) NOT NULL,
    [FAAMBP]     FLOAT (53) NOT NULL,
    [C_FAAMBP]   FLOAT (53) NOT NULL,
    [FOND_CONTR] FLOAT (53) NOT NULL,
    [TOT_CUANT_] FLOAT (53) NOT NULL,
    [CAZ_G1]     INT        NOT NULL,
    [CAZ_G2]     INT        NOT NULL,
    [CAZ_G3]     INT        NOT NULL,
    [CAZ_G4]     INT        NOT NULL,
    [CAZ_G5]     INT        NOT NULL,
    [ZI_PRE_G1]  INT        NOT NULL,
    [ZI_PRE_G2]  INT        NOT NULL,
    [ZI_PRE_G3]  INT        NOT NULL,
    [ZI_PRE_G4]  INT        NOT NULL,
    [ZI_PRE_G5]  INT        NOT NULL,
    [ZI_FN_G1]   INT        NOT NULL,
    [ZI_FN_G2]   INT        NOT NULL,
    [ZI_FN_G3]   INT        NOT NULL,
    [ZI_FN_G4]   INT        NOT NULL,
    [ZI_FN_G5]   INT        NOT NULL,
    [FN_G1]      FLOAT (53) NOT NULL,
    [FN_G2]      FLOAT (53) NOT NULL,
    [FN_G3]      FLOAT (53) NOT NULL,
    [FN_G4]      FLOAT (53) NOT NULL,
    [FN_G5]      FLOAT (53) NOT NULL,
    [TOT_ANTER]  FLOAT (53) NOT NULL,
    [COMPENSAT]  FLOAT (53) NOT NULL,
    [TOT_VIRAT]  FLOAT (53) NOT NULL,
    [TOT_RECUP]  FLOAT (53) NOT NULL,
    [ADR_LOC]    CHAR (25)  NOT NULL,
    [ADR_STR]    CHAR (25)  NOT NULL,
    [ADR_NR]     CHAR (10)  NOT NULL,
    [ADR_BL]     CHAR (10)  NOT NULL,
    [ADR_SC]     CHAR (5)   NOT NULL,
    [ADR_ET]     CHAR (2)   NOT NULL,
    [ADR_AP]     CHAR (3)   NOT NULL,
    [ADR_TEL]    CHAR (15)  NOT NULL,
    [ADR_JUD]    CHAR (2)   NOT NULL,
    [ADR_SECT]   SMALLINT   NOT NULL,
    [E_MAIL]     CHAR (50)  NOT NULL,
    [B1]         CHAR (25)  NOT NULL,
    [F1]         CHAR (25)  NOT NULL,
    [C1]         CHAR (50)  NOT NULL,
    [B2]         CHAR (25)  NOT NULL,
    [F2]         CHAR (25)  NOT NULL,
    [C2]         CHAR (50)  NOT NULL,
    [NRF]        SMALLINT   NOT NULL,
    [TOT_ZI_PRE] FLOAT (53) DEFAULT ((0)) NOT NULL,
    [TOT_SUM]    FLOAT (53) DEFAULT ((0)) NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [Principal]
    ON [dbo].[CMDCLA17]([AN] ASC, [LN] ASC, [TIPD] ASC, [CAS_ANG] ASC);

