CREATE TABLE [dbo].[sysspdev] (
    [Host_id]             VARCHAR (10)    NULL,
    [Host_name]           VARCHAR (30)    NULL,
    [Aplicatia]           VARCHAR (30)    NULL,
    [Data_operarii]       DATETIME2 (3)   NULL,
    [Utilizator]          VARCHAR (10)    NULL,
    [Tip_act]             VARCHAR (1)     NULL,
    [Cod_deviz]           VARCHAR (20)    NULL,
    [Pozitie_articol]     SMALLINT        NOT NULL,
    [Tip_articol]         VARCHAR (1)     NULL,
    [Cod_articol]         VARCHAR (20)    NULL,
    [Expandat]            BINARY (1)      NOT NULL,
    [Cantitate_articol]   FLOAT (53)      NOT NULL,
    [Pret_articol]        FLOAT (53)      NOT NULL,
    [Tip_resursa]         VARCHAR (1)     NULL,
    [Cod_resursa]         VARCHAR (20)    NULL,
    [Cantitate_resursa]   FLOAT (53)      NOT NULL,
    [Pret_resursa]        FLOAT (53)      NOT NULL,
    [Cod_corespondent]    VARCHAR (20)    NULL,
    [Subcapitol]          VARCHAR (9)     NULL,
    [Furnizor]            VARCHAR (13)    NULL,
    [Data_lansarii]       DATETIME2 (3)   NULL,
    [Data_inchiderii]     DATETIME2 (3)   NULL,
    [Coeficient_manopera] FLOAT (53)      NOT NULL,
    [Coeficient_resurse]  NUMERIC (16, 6) NOT NULL,
    [Comasare]            VARCHAR (20)    NULL,
    [Alfa1]               VARCHAR (20)    NULL,
    [Alfa2]               VARCHAR (20)    NULL,
    [Utilizator_dev]      VARCHAR (10)    NULL,
    [Data_operarii_dev]   DATETIME2 (3)   NULL,
    [Ora_operarii]        VARCHAR (6)     NULL
) ON [SYSS];

