CREATE TABLE [dbo].[syssip] (
    [Host_id]                 VARCHAR (10)  NULL,
    [Host_name]               VARCHAR (30)  NULL,
    [Aplicatia]               VARCHAR (30)  NULL,
    [Data_stergerii]          DATETIME2 (7) NULL,
    [Stergator]               VARCHAR (10)  NULL,
    [Tip_act]                 VARCHAR (1)   NULL,
    [Marca]                   VARCHAR (6)   NULL,
    [Permis_auto_categoria]   VARCHAR (10)  NULL,
    [Limbi_straine]           VARCHAR (30)  NULL,
    [Nationalitatea]          VARCHAR (10)  NULL,
    [Cetatenia]               VARCHAR (10)  NULL,
    [Starea_civila]           VARCHAR (1)   NULL,
    [Marca_sot_sotie]         VARCHAR (6)   NULL,
    [Nume_sot_sotie]          VARCHAR (30)  NULL,
    [Religia]                 VARCHAR (25)  NULL,
    [Evidenta_militara]       VARCHAR (1)   NULL,
    [Telefon]                 VARCHAR (15)  NULL,
    [Email]                   VARCHAR (50)  NULL,
    [Observatii]              VARCHAR (100) NULL,
    [Actionar]                BIT           NOT NULL,
    [Centru_de_cost_exceptie] VARCHAR (13)  NULL,
    [Vechime_studii]          VARCHAR (6)   NULL,
    [Loc_munca_precedent]     VARCHAR (40)  NULL,
    [Loc_munca_nou]           VARCHAR (40)  NULL,
    [Vechime_la_intrare]      VARCHAR (6)   NULL,
    [Vechime_in_meserie]      VARCHAR (6)   NULL,
    [Nr_contract]             VARCHAR (20)  NULL,
    [Spor_cond_7]             FLOAT (53)    NOT NULL,
    [Spor_cond_8]             FLOAT (53)    NOT NULL,
    [Spor_cond_9]             FLOAT (53)    NOT NULL,
    [Spor_cond_10]            FLOAT (53)    NOT NULL
) ON [SYSS];

