CREATE TABLE [dbo].[sysss] (
    [Host_id]                       VARCHAR (10)  NULL,
    [Host_name]                     VARCHAR (30)  NULL,
    [Aplicatia]                     VARCHAR (30)  NULL,
    [Data_stergerii]                DATETIME2 (7) NULL,
    [Stergator]                     VARCHAR (10)  NULL,
    [Marca]                         VARCHAR (6)   NULL,
    [Nume]                          VARCHAR (50)  NULL,
    [Cod_functie]                   VARCHAR (6)   NULL,
    [Loc_de_munca]                  VARCHAR (9)   NULL,
    [Loc_de_munca_din_pontaj]       BIT           NOT NULL,
    [Categoria_salarizare]          VARCHAR (4)   NULL,
    [Grupa_de_munca]                VARCHAR (1)   NULL,
    [Salar_de_incadrare]            FLOAT (53)    NOT NULL,
    [Salar_de_baza]                 FLOAT (53)    NOT NULL,
    [Salar_orar]                    FLOAT (53)    NOT NULL,
    [Tip_salarizare]                VARCHAR (1)   NULL,
    [Tip_impozitare]                VARCHAR (1)   NULL,
    [Pensie_suplimentara]           SMALLINT      NOT NULL,
    [Somaj_1]                       SMALLINT      NOT NULL,
    [As_sanatate]                   SMALLINT      NOT NULL,
    [Indemnizatia_de_conducere]     FLOAT (53)    NOT NULL,
    [Spor_vechime]                  REAL          NOT NULL,
    [Spor_de_noapte]                REAL          NOT NULL,
    [Spor_sistematic_peste_program] REAL          NOT NULL,
    [Spor_de_functie_suplimentara]  FLOAT (53)    NOT NULL,
    [Spor_specific]                 FLOAT (53)    NOT NULL,
    [Spor_conditii_1]               FLOAT (53)    NOT NULL,
    [Spor_conditii_2]               FLOAT (53)    NOT NULL,
    [Spor_conditii_3]               FLOAT (53)    NOT NULL,
    [Spor_conditii_4]               FLOAT (53)    NOT NULL,
    [Spor_conditii_5]               FLOAT (53)    NOT NULL,
    [Spor_conditii_6]               FLOAT (53)    NOT NULL,
    [Sindicalist]                   BIT           NOT NULL,
    [Salar_lunar_de_baza]           FLOAT (53)    NOT NULL,
    [Zile_concediu_de_odihna_an]    SMALLINT      NOT NULL,
    [Zile_concediu_efectuat_an]     SMALLINT      NOT NULL,
    [Zile_absente_an]               SMALLINT      NOT NULL,
    [Vechime_totala]                DATETIME2 (3) NULL,
    [Data_angajarii_in_unitate]     DATETIME2 (3) NULL,
    [Banca]                         VARCHAR (25)  NULL,
    [Cont_in_banca]                 VARCHAR (25)  NULL,
    [Sex]                           BIT           NOT NULL,
    [Data_nasterii]                 DATETIME2 (3) NULL,
    [Cod_numeric_personal]          VARCHAR (13)  NULL,
    [Studii]                        VARCHAR (10)  NULL,
    [Profesia]                      VARCHAR (10)  NULL,
    [Adresa]                        VARCHAR (30)  NULL,
    [Copii]                         VARCHAR (30)  NULL,
    [Loc_ramas_vacant]              BIT           NOT NULL,
    [Localitate]                    VARCHAR (30)  NULL,
    [Judet]                         VARCHAR (15)  NULL,
    [Strada]                        VARCHAR (25)  NULL,
    [Numar]                         VARCHAR (5)   NULL,
    [Cod_postal]                    INT           NOT NULL,
    [Bloc]                          VARCHAR (10)  NULL,
    [Scara]                         VARCHAR (2)   NULL,
    [Etaj]                          VARCHAR (2)   NULL,
    [Apartament]                    VARCHAR (5)   NULL,
    [Sector]                        SMALLINT      NOT NULL,
    [Mod_angajare]                  VARCHAR (1)   NULL,
    [Data_plec]                     DATETIME2 (3) NULL,
    [Tip_colab]                     VARCHAR (3)   NULL,
    [grad_invalid]                  VARCHAR (1)   NULL,
    [coef_invalid]                  REAL          NOT NULL,
    [alte_surse]                    BIT           NOT NULL
) ON [SYSS];

