CREATE TABLE [dbo].[sysspp] (
    [Host_id]                 VARCHAR (10)  NULL,
    [Host_name]               VARCHAR (30)  NULL,
    [Aplicatia]               VARCHAR (30)  NULL,
    [Data_stergerii]          DATETIME2 (7) NULL,
    [Stergator]               VARCHAR (10)  NULL,
    [Data_operarii]           DATETIME2 (3) NULL,
    [Ora_operarii]            VARCHAR (6)   NULL,
    [Subunitate]              VARCHAR (9)   NULL,
    [Cont]                    VARCHAR (20)  NULL,
    [Data]                    DATETIME2 (3) NULL,
    [Numar]                   VARCHAR (10)  NULL,
    [Plata_incasare]          VARCHAR (2)   NULL,
    [Tert]                    VARCHAR (13)  NULL,
    [Factura]                 VARCHAR (20)  NULL,
    [Cont_corespondent]       VARCHAR (20)  NULL,
    [Suma]                    FLOAT (53)    NOT NULL,
    [Valuta]                  VARCHAR (3)   NULL,
    [Curs]                    FLOAT (53)    NOT NULL,
    [Suma_valuta]             FLOAT (53)    NOT NULL,
    [Curs_la_valuta_facturii] FLOAT (53)    NOT NULL,
    [TVA11]                   FLOAT (53)    NOT NULL,
    [TVA22]                   FLOAT (53)    NOT NULL,
    [Explicatii]              VARCHAR (50)  NULL,
    [Loc_de_munca]            VARCHAR (9)   NULL,
    [Comanda]                 VARCHAR (20)  NULL,
    [Utilizator]              VARCHAR (10)  NULL,
    [Numar_pozitie]           INT           NOT NULL,
    [Cont_dif]                VARCHAR (20)  NULL,
    [Suma_dif]                FLOAT (53)    NOT NULL,
    [Achit_fact]              FLOAT (53)    NOT NULL,
    [Jurnal]                  VARCHAR (3)   NULL
) ON [SYSS];

