CREATE TABLE [dbo].[sysspcon] (
    [Host_id]              VARCHAR (10)  NULL,
    [Host_name]            VARCHAR (30)  NULL,
    [Aplicatia]            VARCHAR (30)  NULL,
    [Data_stergerii]       DATETIME2 (7) NULL,
    [Stergator]            VARCHAR (10)  NULL,
    [Data_operarii]        DATETIME2 (3) NULL,
    [Ora_operarii]         VARCHAR (6)   NULL,
    [Subunitate]           VARCHAR (9)   NULL,
    [Tip]                  VARCHAR (2)   NULL,
    [Contract]             VARCHAR (20)  NULL,
    [Tert]                 VARCHAR (13)  NULL,
    [Punct_livrare]        VARCHAR (13)  NULL,
    [Data]                 DATETIME2 (3) NULL,
    [Cod]                  VARCHAR (20)  NULL,
    [Cantitate]            FLOAT (53)    NOT NULL,
    [Pret]                 FLOAT (53)    NOT NULL,
    [Pret_promotional]     FLOAT (53)    NOT NULL,
    [Discount]             REAL          NOT NULL,
    [Termen]               DATETIME2 (3) NULL,
    [Factura]              VARCHAR (20)  NULL,
    [Cant_disponibila]     FLOAT (53)    NOT NULL,
    [Cant_aprobata]        FLOAT (53)    NOT NULL,
    [Cant_realizata]       FLOAT (53)    NOT NULL,
    [Valuta]               VARCHAR (3)   NULL,
    [Cota_TVA]             SMALLINT      NOT NULL,
    [Suma_TVA]             FLOAT (53)    NOT NULL,
    [Mod_de_plata]         VARCHAR (8)   NULL,
    [UM]                   VARCHAR (1)   NULL,
    [Zi_scadenta_din_luna] SMALLINT      NOT NULL,
    [Explicatii]           VARCHAR (50)  NULL,
    [Numar_pozitie]        INT           NOT NULL,
    [Utilizator]           VARCHAR (10)  NULL
) ON [SYSS];

