CREATE TABLE [dbo].[sysspozactiv] (
    [Host_id]        VARCHAR (10)  NULL,
    [Host_name]      VARCHAR (30)  NULL,
    [Aplicatia]      VARCHAR (30)  NULL,
    [Data_stergerii] DATETIME2 (7) NULL,
    [Stergator]      VARCHAR (10)  NULL,
    [Tip_act]        VARCHAR (1)   NULL,
    [Tip]            VARCHAR (2)   NULL,
    [Fisa]           VARCHAR (20)  NULL,
    [Data]           DATETIME2 (3) NULL,
    [Numar_pozitie]  INT           NOT NULL,
    [Traseu]         VARCHAR (20)  NULL,
    [Plecare]        VARCHAR (30)  NULL,
    [Data_plecarii]  DATETIME2 (3) NULL,
    [Ora_plecarii]   VARCHAR (6)   NULL,
    [Sosire]         VARCHAR (30)  NULL,
    [Data_sosirii]   DATETIME2 (3) NULL,
    [Ora_sosirii]    VARCHAR (6)   NULL,
    [Explicatii]     VARCHAR (50)  NULL,
    [Comanda_benef]  VARCHAR (13)  NULL,
    [Lm_beneficiar]  VARCHAR (9)   NULL,
    [Tert]           VARCHAR (13)  NULL,
    [Marca]          VARCHAR (6)   NULL,
    [Utilizator]     VARCHAR (10)  NULL,
    [Data_operarii]  DATETIME2 (3) NULL,
    [Ora_operarii]   VARCHAR (6)   NULL,
    [Alfa1]          VARCHAR (50)  NULL,
    [Alfa2]          VARCHAR (50)  NULL,
    [Val1]           FLOAT (53)    NOT NULL,
    [Val2]           FLOAT (53)    NOT NULL,
    [Data1]          DATETIME2 (3) NULL
) ON [SYSS];

