CREATE TABLE [dbo].[sysspa] (
    [Host_id]         VARCHAR (10)  NULL,
    [Host_name]       VARCHAR (30)  NULL,
    [Aplicatia]       VARCHAR (30)  NULL,
    [Data_stergerii]  DATETIME2 (7) NULL,
    [Stergator]       VARCHAR (10)  NULL,
    [Data_operarii]   DATETIME2 (3) NULL,
    [Ora_operarii]    VARCHAR (6)   NULL,
    [Subunitate]      VARCHAR (9)   NULL,
    [Numar_document]  VARCHAR (8)   NULL,
    [Data]            DATETIME2 (3) NULL,
    [Tert]            VARCHAR (13)  NULL,
    [Tip]             VARCHAR (2)   NULL,
    [Factura_stinga]  VARCHAR (20)  NULL,
    [Factura_dreapta] VARCHAR (20)  NULL,
    [Cont_deb]        VARCHAR (20)  NULL,
    [Cont_cred]       VARCHAR (20)  NULL,
    [Suma]            FLOAT (53)    NOT NULL,
    [TVA11]           FLOAT (53)    NOT NULL,
    [TVA22]           FLOAT (53)    NOT NULL,
    [Utilizator]      VARCHAR (10)  NULL,
    [Numar_pozitie]   INT           NOT NULL,
    [Tert_beneficiar] VARCHAR (13)  NULL,
    [Explicatii]      VARCHAR (50)  NULL,
    [Valuta]          VARCHAR (3)   NULL,
    [Curs]            FLOAT (53)    NOT NULL,
    [Suma_valuta]     FLOAT (53)    NOT NULL,
    [Cont_dif]        VARCHAR (20)  NULL,
    [suma_dif]        FLOAT (53)    NOT NULL,
    [Loc_munca]       VARCHAR (9)   NULL,
    [Comanda]         VARCHAR (20)  NULL,
    [Data_fact]       DATETIME2 (3) NULL,
    [Data_scad]       DATETIME2 (3) NULL,
    [Stare]           SMALLINT      NOT NULL,
    [Achit_fact]      FLOAT (53)    NOT NULL,
    [Dif_TVA]         FLOAT (53)    NOT NULL,
    [Jurnal]          VARCHAR (3)   NULL
) ON [SYSS];

