CREATE TABLE [dbo].[syssn] (
    [Host_id]                VARCHAR (10)  NULL,
    [Host_name]              VARCHAR (30)  NULL,
    [Aplicatia]              VARCHAR (30)  NULL,
    [Data_stergerii]         DATETIME2 (7) NULL,
    [Stergator]              VARCHAR (10)  NULL,
    [Cod]                    VARCHAR (20)  NULL,
    [Tip]                    VARCHAR (1)   NULL,
    [Denumire]               VARCHAR (80)  NULL,
    [UM]                     VARCHAR (3)   NULL,
    [UM_1]                   VARCHAR (3)   NULL,
    [Coeficient_conversie_1] FLOAT (53)    NOT NULL,
    [UM_2]                   VARCHAR (20)  NULL,
    [Coeficient_conversie_2] FLOAT (53)    NOT NULL,
    [Cont]                   VARCHAR (20)  NULL,
    [Grupa]                  VARCHAR (13)  NULL,
    [Valuta]                 VARCHAR (3)   NULL,
    [Pret_in_valuta]         FLOAT (53)    NOT NULL,
    [Pret_stoc]              FLOAT (53)    NOT NULL,
    [Pret_vanzare]           FLOAT (53)    NOT NULL,
    [Pret_cu_amanuntul]      FLOAT (53)    NOT NULL,
    [Cota_TVA]               SMALLINT      NOT NULL,
    [Stoc_limita]            FLOAT (53)    NOT NULL,
    [Stoc]                   FLOAT (53)    NOT NULL,
    [Greutate_specifica]     FLOAT (53)    NOT NULL,
    [Furnizor]               VARCHAR (13)  NULL,
    [Loc_de_munca]           VARCHAR (150) NULL,
    [Gestiune]               VARCHAR (13)  NULL,
    [Categorie]              SMALLINT      NOT NULL,
    [Tip_echipament]         VARCHAR (21)  NULL
) ON [SYSS];

