CREATE TABLE [dbo].[totlocb] (
    [Data_tot]                       DATETIME   NOT NULL,
    [Marca_tot]                      CHAR (6)   NOT NULL,
    [Loc_de_munca_tot]               CHAR (9)   NOT NULL,
    [Loc_munca_pt_stat_de_plata_tot] BIT        NOT NULL,
    [Total_ore_lucrate_tot]          INT        NOT NULL,
    [Ore_lucrate_TESA_regie_tot]     FLOAT (53) NOT NULL,
    [Realizat_TESA_regie_tot]        FLOAT (53) NOT NULL,
    [Ore_lucrate_acord_tot]          FLOAT (53) NOT NULL,
    [Realizat_acord_tot]             FLOAT (53) NOT NULL,
    [Ore_suplimentare_1_tot]         FLOAT (53) NOT NULL,
    [Indemnizatie_ore_supl_1_tot]    FLOAT (53) NOT NULL,
    [Ore_suplimentare_2_tot]         FLOAT (53) NOT NULL,
    [Indemnizatie_ore_supl_2_tot]    FLOAT (53) NOT NULL,
    [Ore_suplimentare_3_tot]         FLOAT (53) NOT NULL,
    [Indemnizatie_ore_supl_3_tot]    FLOAT (53) NOT NULL,
    [Ore_suplimentare_4_tot]         FLOAT (53) NOT NULL,
    [Indemnizatie_ore_supl_4_tot]    FLOAT (53) NOT NULL,
    [Ore_spor_100_tot]               FLOAT (53) NOT NULL,
    [Indemniz_spor_100_tot]          FLOAT (53) NOT NULL,
    [Ore_de_noapte_tot]              FLOAT (53) NOT NULL,
    [Ind_ore_de_noapte_tot]          FLOAT (53) NOT NULL,
    [Ore_lucrate_regim_normal_tot]   FLOAT (53) NOT NULL,
    [Ind_regim_normal_tot]           FLOAT (53) NOT NULL,
    [Ore_intrerupere_tehn_tot]       FLOAT (53) NOT NULL,
    [Ind__intrerupere_tehn_tot]      FLOAT (53) NOT NULL,
    [Ore_obligatii_cetatenesti_tot]  FLOAT (53) NOT NULL,
    [Ind_obligatii_cetatenesti_tot]  FLOAT (53) NOT NULL,
    [Ore_concediu_fara_salar_tot]    FLOAT (53) NOT NULL,
    [Ind_concediu_fara_salar_tot]    FLOAT (53) NOT NULL,
    [Ore_concediu_de_odihna_tot]     FLOAT (53) NOT NULL,
    [Ind_concediu_de_odihna_tot]     FLOAT (53) NOT NULL,
    [Ore_concediu_medical_tot]       FLOAT (53) NOT NULL,
    [Ind_c_medical_unitate_tot]      FLOAT (53) NOT NULL,
    [Ind_c_medical_CAS_tot]          FLOAT (53) NOT NULL,
    [Ore_invoiri_tot]                FLOAT (53) NOT NULL,
    [Ind_invoiri_tot]                FLOAT (53) NOT NULL,
    [Ore_nemotivate_tot]             FLOAT (53) NOT NULL,
    [Ind_nemotivate_tot]             FLOAT (53) NOT NULL,
    [Salar_categoria_lucrarii_tot]   FLOAT (53) NOT NULL,
    [CMCAS_tot]                      FLOAT (53) NOT NULL,
    [CMunitate_tot]                  FLOAT (53) NOT NULL,
    [CO_tot]                         FLOAT (53) NOT NULL,
    [Restituiri_tot]                 FLOAT (53) NOT NULL,
    [Diminuari_tot]                  FLOAT (53) NOT NULL,
    [Suma_impozabila_tot]            FLOAT (53) NOT NULL,
    [Premiu_tot]                     FLOAT (53) NOT NULL,
    [Diurna_tot]                     FLOAT (53) NOT NULL,
    [Cons_admin_tot]                 FLOAT (53) NOT NULL,
    [Sp_salar_realizat_tot]          FLOAT (53) NOT NULL,
    [Suma_imp_separat_tot]           FLOAT (53) NOT NULL,
    [CO2_tot]                        FLOAT (53) NOT NULL,
    [Spor_vechime_tot]               FLOAT (53) NOT NULL,
    [Spor_de_noapte_tot]             FLOAT (53) NOT NULL,
    [Spor_sistematic_peste_prog_tot] FLOAT (53) NOT NULL,
    [Spor_de_functie_suplim_tot]     FLOAT (53) NOT NULL,
    [Spor_specific_tot]              FLOAT (53) NOT NULL,
    [Spor_cond_1_tot]                FLOAT (53) NOT NULL,
    [Spor_cond_2_tot]                FLOAT (53) NOT NULL,
    [Spor_cond_3_tot]                FLOAT (53) NOT NULL,
    [Spor_cond_4_tot]                FLOAT (53) NOT NULL,
    [Spor_cond_5_tot]                FLOAT (53) NOT NULL,
    [Spor_cond_6_tot]                FLOAT (53) NOT NULL,
    [Spor_cond_7_tot]                FLOAT (53) NOT NULL,
    [Spor_cond_8_tot]                FLOAT (53) NOT NULL,
    [Compensatie_tot]                FLOAT (53) NOT NULL,
    [VENIT_TOTAL_tot]                FLOAT (53) NOT NULL,
    [Nr_pers_tot]                    INT        NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [Data_Marca_Locm]
    ON [dbo].[totlocb]([Data_tot] ASC, [Marca_tot] ASC, [Loc_de_munca_tot] ASC);


GO
CREATE NONCLUSTERED INDEX [Locm]
    ON [dbo].[totlocb]([Loc_de_munca_tot] ASC);

